# Ensure that we only run ci test on the Node.js enabled servers.
language: node_js
node_js:
  - "0.8"
  - "0.10"

# Create a travis 

services: memcache


before_script:
  - memcached -p 11212 -d
  - memcached -p 11213 -d
